### ISSUE TITLE
"Autonomous Adaptation to a new scene" in the article.

### ISSUE THREAD

**Issue by jeonggwanlee** [PierreMarza/autonerf#3]
Hi,
Thank you for sharing your great works.

I read your paper and had questions in "5.2 Autonomous Adaptation to a new scene" part.
https://openreview.net/forum?id=qVBTlo0T4s&referrer=%5Bthe%20profile%20of%20Olivier%20Simonin%5D(%2Fprofile%3Fid%3D~Olivier_Simonin1)

What I understand is below.

The purpose of 5.2 section is to show adaptation on a new scene setting which creates AutoNeRF mesh on a new scene (Gibson val scene), load that mesh in the Habitat sim, and do policy learning (fine-tuning) on that mesh, not the true mesh.
What I didn't understand is, How to utilize AutoNeRF mesh on Gibson val scene even though we didn't collect any eco-centric images in val scene.

What I imagined (to make sense) is, 
1) Collect eco-centric images in val scene with pretrained policy (with time budget; like 1500 steps)
2) Using that images, train AutoNeRF
3) Generate AutoNeRF mesh of val scene using AutoNeRF
4) Fine-tune the pre-trained policy on the AtoNeRF mesh of val scene

Is it correct? or If I misunderstand some parts, please let me know!
It would be very helpful to understand your works!

And, is there some related executable code in the github? If there is, please let me know :) 

Another question is, In page 8, "5.2 Autonomous Adaptation to a new scene"
The sentence "More specifically, we consider a policy for an agent taking a depth frame as input at each timestep t and pre-train it on PointGoal navigation on the Gibson train scenes."

"a depth frame" is needed because of semantic mapping module?

Thanks.

**Comment by PierreMarza** [comment]
Hi,

Thank you for your great questions!

Section 5.2 is about using AutoNeRF as a way to scan a previously unseen environment so that we can fine-tune any **other** policy of interest on this specific scene. The final goal would be to do this in a new environment for which we don’t have a ground-truth mesh already. 

To simulate such a use case, we consider a PointGoal policy navigating from depth inputs that was pre-trained on a set of scenes from Gibson train. When deployed on new scenes, the policy might struggle with some specificities of these scenes. We emulate this scenario with Gibson val scenes, as if we didn’t have access to their meshes (using Gibson meshes is considered as an upper bound).

The steps 1, 2 and 3 you mentioned are right. The fourth one is about fine-tuning an external policy (in our example, a depth-only PointGoal policy), and not AutoNeRF policy. The code allows you to perform steps from 1 to 3 (data collection on a new scene, NeRF training, mesh generation). Once you have a mesh, you can load it into a simulator (in our experiments we did it in Habitat) and fine-tune any policy you might be interested in (in our case a pre-trained depth-only PointGoal policy).

I hope this answers your questions. Let me know if you need any clarifications!

**Comment by jeonggwanlee** [comment]
Hi, Pierre.

Thank you for great answers!
It helps a lot to understand your work.

Can you let me know the structure of PointGoal policy? (is it like a Modular Policy structure in your paper?)
and I expect that "PointGoal policy" and external policy is same, is it true?

**Comment by PierreMarza** [comment]
Hi,

The autonomous adaptation can be applied to any policy, independently of the modular AutoNeRF policy (the latter being only used to gather data to reconstruct scenes of interest). To showcase this point, we used here an end-to-end depth-only PointGoal policy that is not modular (different from the AutoNeRF policy). More specifically, we used a baseline end-to-end policy from ‘habitat_baselines’ (see https://github.com/facebookresearch/habitat-lab/tree/v0.2.1/habitat_baselines). Pre-trained policies can be downloaded from https://dl.fbaipublicfiles.com/habitat/data/baselines/v1/habitat_baselines_v2.zip. We fine-tuned the ‘gibson-depth-best.pth’ variant on meshes generated from AutoNeRF for 4 Gibson val scenes (Corozal, Darden, Markleeville, Wiconisco).

Let me know if you have other questions!
